language: android
before_install:
- openssl aes-256-cbc -K $encrypted_57b46cc7e937_key -iv $encrypted_57b46cc7e937_iv
  -in debug.keystore.enc -out ./android/app/debug.keystore -d
- nvm install 9
- node --version
install:
- npm install
- npm install -g react-native-cli
- npm i jetifier
android:
  components:
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
- npx jetify
- react-native bundle --platform android --dev false --entry-file index.js --bundle-output
  android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
- cd android && ./gradlew assembleRelease -x bundleReleaseJsAndAssets
deploy:
  provider: releases
    skip_cleanup: true
  api_key:
    secure: mSdTCVZmOn21k68TQfPdD0fw+gXPjpoyAqe8ayIxygmtLbI6v+OONWiBhH5L32SwjvfFlSn92N8QnK2gTyoFZZ/eYPCKBo5BXqkoxtVshRedV20TNSh/jIkfeXHqnJ2BbANMGzzwVNw0WoGqaaEL8QXuklt5iZDamR/cOwMri5whj7qRA8OK+q361cDpPAldrrfNU0OZ3ASKLjGOJycXfOWcC6yLO0sLdowrQtJ8JBEGjvKs/3IqwZIbaZr6Xnlq93zStqwYC5Z8LG18srfkVzBqWEGF4jnFze+hahMmYw+jxNhntyr/LULFc3yUvzKmw7j+FTZ5SlqqlZszh5V/0KzzBU47XRmAt9EP+iBv9F/EQeOVaeQJU34jC1b0Mhu0mMN1rzh5vWKQFgFVdnnVbAq7oz13TD/QB/SCYlr86dXB+mTyJAc4IHaaYXCnVUAZzGsROmDroi0SS+IOUJ80/cyHrG+IdWRa8MXyR4QeKgdPErHt9F0n+kmsl7Bhyni/kNvwQGUzUAvns8YxtuB8JHuy9QncaVwB83RdWUwoi5LdPVe8wos4aD7e5E3we6Tp0fTNB1ZuYQcIvs6lHdk8PKgV9o5/+wCXVtYD2JW2d4gH3k9ZCveC47qbaXNztlQtlkiXUrry73Sc7qAdmqZtpoU8xhvTVR3sbS8xMHzc4qM=
  file: "$TRAVIS_BUILD_DIR/android/app/build/outputs/apk/release/app-release.apk"
  on:
    repo: setuperoner/LastTest
    tags: true
notifications:
  email:
    recipients:
    - obc993@gmail.com
    on_failure: change
    on_success: change
