language: android
before_install:
- openssl aes-256-cbc -K $encrypted_57b46cc7e937_key -iv $encrypted_57b46cc7e937_iv
  -in debug.keystore.enc -out ./android/app/debug.keystore -d
- nvm install 9
- node --version
install:
- npm install
- npm install -g react-native-cli
- npm i jetifier
android:
  components:
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
- npx jetify
- react-native bundle --platform android --dev false --entry-file index.js --bundle-output
  android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
- cd android && ./gradlew assembleRelease -x bundleReleaseJsAndAssets
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    ssecure: XcsHzS4AlHrjzm28nNgS+QswZNDwtDpZ/AW/k08BPuOuAsslJTlPfv2DaHzSLkclU3JXA+Vj6HPX8bTrplTiFdqzNayV1g3bd+JciU5TLy7SZkMA5r262oy1hHq5ixYaeIoy6EaK02CBXxgWnZ2EazF0Bsb4CGASTC5vI9ngyAsbhIr2dEK6Z0IBabsmNRdh8qAIgVjNFQ5d83HyGiwE9HPg6QGEk/LLQq1Zu2tdSbHING0lS1MMkUr4cui2uC4dvl9UllT9DmDiraCW5FQCCPiR56LGOYxXL5fKDHcBEOXnFzPSJtVqE9ny64mQA/91a2CPySmTsQak27x4s3ALIGNjWcNs3lApRrXcrwjqjB0QY74dgH//Dt0+mJmDZ65iHtAsC8jZXyTbYXLo+jQ27/D4/NJc4tKhwLKiebwTTH7lDI2cPQPIQJz3jgW83WobKfqDajKpqsekvsvX5g0urUv3pJu1o2CVy0GWi+x9YXoyhBfOJbKFhw9Qp1oRhm3+2kHab/Rj2/5rkkSZhhTq0kX/HC7Ob3Gb6uniy0kRWcLKYA3eG3EwzNmku2tsB3sAh28vpmm6NOZ5lD/3ZagnHQdo7Ee4jNyEB+f8GLfcDuns9o0pnPV40ifiUJlRbhIwl9w3d9uduPxhneCU0sZaD8Tq63gAf/3N/oj2TPyhkU8=
  file: "$TRAVIS_BUILD_DIR/android/app/build/outputs/apk/release/app-release.apk"
  on:
    repo: setuperoner/TestRepo
    tags: true
notifications:
  email:
    recipients:
    - obc993@gmail.com
    on_failure: change
    on_success: change
